### PR TITLE
Added GoReportCard badge

### PR DESCRIPTION
**Pull request by Hoenn**
Might as well show it off!

### CODE REVIEW

**Comment by brunomvsouza** [comment]
Thank you for the contribution @Hoenn! :)

Can you please add a space between the previous card and the newly added Go Report Card? From: `...ynab.go)[![Go Report Card]...` to `...ynab.go) [![Go Report Card]...`.

**Comment by brunomvsouza** [comment]
See https://github.com/brunomvsouza/ynab.go/pull/16.

**Comment by Hoenn** [comment]
@brunomvsouza didn't have notifications on, sorry I didn't add the space! I added your report card badge so I could link your project in [awesome-go](https://github.com/avelino/awesome-go/pull/2122) . I used your API wrapper for my [ynab-metrics](https://github.com/Hoenn/ynab-metrics) prometheus exporter, your wrapper was great!

**Comment by brunomvsouza** [comment]
Hey @Hoenn! Thank you for taking your time to suggest this lib on Avelino's list. I appreciate it. 🍻

I took a look at https://github.com/Hoenn/ynab-metrics, I liked it 👍! I have never thought of using prometheus + Grafana for that purpose. 

Glad you enjoyed using it. If you have any other feedback please let me know. :)

**Pull request closed without merging**
